### PR TITLE
Add rspec-tests for all classes

### PR DESCRIPTION
**Pull request by gerhardsam**

### CODE REVIEW

**Comment by gwarf** [comment]
Hi @gerhardsam thanks for all this hard work, I will check ant test this ASAP!

**Comment by gwarf** [comment]
Merged, thanks a lot!

**Comment by gerhardsam** [comment]
You are welcome! And thanks for merging :-)

**Comment by gwarf** [comment]
There is more module missing tests, don't hesitate to do some more PR like this one ;)

**Pull request merged**
